knp_gaufrette:
  stream_wrapper: ~

  adapters:
    marque_adapter:
      local:
        directory: "%kernel.project_dir%/public/images/marques"

  filesystems:
    marque_fs:
      adapter: marque_adapter

vich_uploader:
  db_driver: orm
  storage: gaufrette

  metadata:
    type: attribute

  mappings:
    marques:
      uri_prefix: /images/marques
      upload_destination: marque_fs
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
